### ISSUE TITLE
Sample works great ! But..changes made to code is not good

### ISSUE THREAD

**Issue by Nuthalapati** [awslabs/eb-locustio-sample#6]
This is a great example and it worked all great !

I have modified the code and checked-in to my repo and started fresh in an instance then I see this problem.

Its not able set the environment name and also couldn't get the master ip table. 

When I try to manually set it via elastic beanstalk UI, it still rejects it and throws the same error.

Any help is appreciated. 

15:23:29 build.1 | ./build.rb:63:in `+': no implicit conversion of Fixnum into String (TypeError)
  15:23:29 build.1 | 	from ./build.rb:63:in `main'
  15:23:29 build.1 | 	from ./build.rb:173:in `<main>'
  15:23:29 build.1 | Error retrieving number of instances in 
  15:23:29 build.1 | You must specify either EnvironmentName or EnvironmentId.
  15:23:29 build.1 | Error writing master IP to 
  15:23:29 build.1 | undefined method `*' for nil:NilClass
  15:23:29 build.1 | We are follower
  15:23:29 build.1 | Read Attempt 1
  15:23:29 build.1 | Error reading master IP from 
  15:23:29 build.1 | missing required parameter params[:table_name]
  15:23:29 build.1 | Read Attempt 2
  15:23:29 build.1 | Error reading master IP from 
  15:23:29 build.1 | missing required parameter params[:table_name]
  15:23:29 build.1 | Read Attempt 3
  15:23:29 build.1 | Error reading master IP from 
  15:23:29 build.1 | missing required parameter params[:table_name]
  15:23:29 build.1 | Read Attempt 4
  15:23:29 build.1 | Error reading master IP from 
  15:23:29 build.1 | missing required parameter params[:table_name]
  15:23:29 build.1 | Read Attempt 5
  15:23:29 build.1 | Error reading master IP from 
  15:23:29 build.1 | missing required parameter params[:table_name]
  15:23:29 build.1 | exited with code 1
  15:23:29 system  | sending SIGTERM to all processes

**Comment by abhiksingh** [comment]
@Nuthalapati could you please provide more information on which EB platform are you trying to run this? Could you please try the latest commit and let me know if this problem persists?

**Comment by vipinkumar1234** [comment]
@abhiksingh I am folowing the guide and i am getting error [Instance: i-0f500b81a5318b51b] Command failed on instance. Return code: 1 Output: Engine execution has encountered an error..Attempting to install ['locustio==0.8.1', 'pyzmq==16.0.3'] via easy_install
 [ERROR] easy_install failed. Output: Searching for locustio==0.8.1

any idea how to resolve this...
